name = "newsnow"
pages_build_output_dir = "output/public"
compatibility_date = "2024-10-28"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "mao"
database_id = "76fe931f-0289-4a33-916b-d42904a44769"
